### ISSUE TITLE
Empty component results in almost 300K javascript bundle

### ISSUE THREAD

**Issue by OlegZee** [room-js/typescript-vue-component-boilerplate#4]
This is too much for just blank component. I would expect it somewhat around 3KB.

**Comment by yurist38** [comment]
Can you please provide more details where did you get this number (300K) from? I just checked [the package](https://bundlephobia.com/result?p=@roomjs/vue-shop-item@0.0.17) built with this boilerplate and its size is much smaller than 300K.

**Comment by yurist38** [comment]
This one is also should be fixed after the last change.
