### ISSUE TITLE
Duplicate Vue instances

### ISSUE THREAD

**Issue by Naartti** [room-js/typescript-vue-component-boilerplate#6]
When building this package and importing into another project there's a error for `$attrs is readonly` and `$listeners is readonly`. These errors tends to occur when importing Vue multiple times (https://stackoverflow.com/questions/52213260/vue-warn-attrs-is-readonly-vue-warn-listeners-is-readonly).

**Comment by yurist38** [comment]
It should be fixed now. Thanks @Naartti for the PR!
